#!/bin/bash
# Select ports for services
#

# Get args
while getopts a: flag
do
    case "${flag}" in
        a) app=${OPTARG};;
    esac
done

# Check required args
if [ -z "$app" ]; then
    echo "⚠️ App is not set – please specify as -a <app-name>" # i.e. -a admin
    exit 1
fi

echo "npm_config_mock is set to '$npm_config_mock'"

# Configure and expose variables
source scripts/aws/configure
export PUBLIC_STAGE=${STAGE}

if [ ${npm_config_mock+x} ]; then

    # Set comma-separated list of services to mock
    services="analytics"

    # Loop over comma-separated string of services
    IFS=',' read -r -a service_list <<< "$services"
    port=3999

    # Todo kill dynamically
    kill -9 $(lsof -ti:4000,4001,4002)

    export PUBLIC_MOCK_ENABLED=$npm_config_mock

    for service in "${service_list[@]}"
    do
        SERVICE=$(echo $service | tr '[:lower:]' '[:upper:]')
        port=$(( port + 1 ))
        export PUBLIC_${SERVICE}_PORT=$port
    done
    scripts/local/mock -d infrastructure/cdk -s $services & npm run dev --workspace @heythanks/$app
else
    npm run dev --workspace @heythanks/$app
fi